"""Server-side setup actions for the web UI: install deps, interactive login.

This is deliberately the most privileged corner of the web tier — it shells out
(`pip install`, `playwright install`) and can open a browser on the host. To keep
that contained:

* every executed command is **derived server-side** from a connector's declared,
  trusted metadata (:attr:`Connector.pip_requirements` /
  ``needs_playwright_browser``) — never from client-supplied strings;
* actions are gated behind ``dbs serve --allow-setup`` (off unless asked for);
* like the rest of the UI it is meant for **localhost, single-user** use.

Jobs run in a background thread and stream log lines over the same SSE machinery
the backup progress view uses. One setup job runs at a time.
"""

from __future__ import annotations

import subprocess
import sys
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from queue import Empty, Queue
from typing import Any, Callable, Iterator

from .jobs import JobAlreadyRunning  # reuse the same "busy" signal

_SENTINEL = object()


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# --------------------------------------------------------------------------- #
# command derivation (pure — unit-tested)                                      #
# --------------------------------------------------------------------------- #


def playwright_present() -> bool:
    """Whether the Playwright Python package is importable (capture needs it)."""
    import importlib.util

    try:
        return importlib.util.find_spec("playwright") is not None
    except (ImportError, ValueError):  # pragma: no cover
        return False


def playwright_install_commands() -> list[tuple[str, list[str]]]:
    """Fixed steps to make browser capture possible (server-derived argv)."""
    return [
        ("pip install playwright", [sys.executable, "-m", "pip", "install", "playwright"]),
        ("playwright install chromium", [sys.executable, "-m", "playwright", "install", "chromium"]),
    ]


def chain_runners(*runners: Callable[[Callable[[str], None]], None]) -> Callable[[Callable[[str], None]], None]:
    """Run several step-runners in order, sharing one log stream."""

    def runner(emit: Callable[[str], None]) -> None:
        for r in runners:
            if r is not None:
                r(emit)

    return runner


def install_commands(rc) -> list[tuple[str, list[str]]]:
    """Build the (label, argv) steps to make a connector runnable.

    Derived entirely from the connector's declared metadata. Returns an empty
    list when nothing needs installing.
    """
    steps: list[tuple[str, list[str]]] = []
    reqs = list(rc.cls.pip_requirements)
    if reqs:
        steps.append(("pip install " + " ".join(reqs),
                      [sys.executable, "-m", "pip", "install", *reqs]))
    if rc.cls.needs_playwright_browser:
        steps.append(("playwright install chromium",
                      [sys.executable, "-m", "playwright", "install", "chromium"]))
    return steps


# --------------------------------------------------------------------------- #
# runners                                                                       #
# --------------------------------------------------------------------------- #


def run_commands(commands: list[tuple[str, list[str]]]) -> Callable[[Callable[[str], None]], None]:
    """A runner that executes each (label, argv) in turn, streaming output."""

    def runner(emit: Callable[[str], None]) -> None:
        for label, argv in commands:
            emit(f"$ {label}")
            proc = subprocess.Popen(
                argv, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1,
            )
            assert proc.stdout is not None
            for line in proc.stdout:
                emit(line.rstrip("\n"))
            code = proc.wait()
            if code != 0:
                raise RuntimeError(f"`{label}` failed (exit {code})")
            emit(f"[ok] {label}")
        emit("Done.")

    return runner


def to_netscape_cookies(cookies: list[dict]) -> str:
    """Format Playwright cookies as a Netscape cookies.txt (what yt-dlp reads)."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by Daily Backup System", ""]
    for c in cookies:
        domain = c.get("domain") or ""
        if not domain or not c.get("name"):
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires", 0) or 0
        expiry = str(int(expires)) if expires and expires > 0 else "0"
        name = c["name"]
        value = c.get("value", "")
        # yt-dlp recognises the #HttpOnly_ prefix for httpOnly cookies.
        dom_field = ("#HttpOnly_" + domain) if c.get("httpOnly") else domain
        lines.append("\t".join([dom_field, include_sub, path, secure, expiry, name, value]))
    return "\n".join(lines) + "\n"


def browser_capture_runner(
    kind: str,
    target: str,
    login_url: str,
    on_success: Callable[[], None],
    *,
    wait_timeout: float = 900.0,
) -> Callable[[Callable[[str], None]], None]:
    """A runner that opens a headed browser for a one-time interactive login.

    The browser opens on the *host running the server* (it cannot render inside
    the web page). The user logs in and closes the window; then:

    * ``browser_session`` — ``target`` is a Playwright persistent-context dir; the
      logged-in cookies are already persisted there on close.
    * ``browser_cookies`` — cookies are exported to a Netscape ``cookies.txt`` at
      ``target`` (snapshotted while the window is open, since cookies can't be
      read after it closes).

    ``on_success`` records the resulting path. Requires a display + Playwright.
    """

    def runner(emit: Callable[[str], None]) -> None:
        from pathlib import Path

        try:
            from playwright.sync_api import sync_playwright
        except ImportError as exc:
            raise RuntimeError(
                "browser capture needs Playwright — install it with "
                "`pip install playwright` and `playwright install chromium`."
            ) from exc

        if kind == "browser_session":
            profile_dir = target
        elif kind == "browser_cookies":
            profile_dir = target + ".profile"  # keep the .txt path clean
        else:
            raise RuntimeError(f"unsupported capture kind: {kind!r}")
        Path(profile_dir).mkdir(parents=True, exist_ok=True)

        emit("Opening a browser window on the server host.")
        emit(f"Log in at {login_url or 'the opened page'}, then CLOSE the window to finish.")
        latest_cookies: list[dict] = []
        with sync_playwright() as p:
            try:
                ctx = p.chromium.launch_persistent_context(profile_dir, headless=False)
            except Exception as exc:  # no display / browser not installed
                raise RuntimeError(
                    f"could not launch a browser ({exc}). The host needs a display and "
                    f"`playwright install chromium`. On a headless server, capture on a "
                    f"desktop and point the secret at the resulting path."
                ) from exc
            closed = threading.Event()
            ctx.on("close", lambda: closed.set())
            page = ctx.pages[0] if ctx.pages else ctx.new_page()
            if login_url:
                try:
                    page.goto(login_url)
                except Exception:  # navigation is best-effort
                    pass
            emit("Waiting for you to finish… (close the browser window when logged in)")
            # Snapshot cookies periodically so we have the latest set at close
            # time (cookies can't be read once the context is gone).
            deadline_loops = int(max(1, wait_timeout))
            for _ in range(deadline_loops):
                if closed.wait(timeout=1.0):
                    break
                if kind == "browser_cookies":
                    try:
                        latest_cookies = ctx.cookies()
                    except Exception:  # noqa: BLE001
                        pass
            if kind == "browser_cookies" and not closed.is_set():
                # Final snapshot if we timed out with the window still open.
                try:
                    latest_cookies = ctx.cookies()
                except Exception:  # noqa: BLE001
                    pass
            try:
                ctx.close()
            except Exception:  # noqa: BLE001
                pass

        if kind == "browser_cookies":
            Path(target).write_text(to_netscape_cookies(latest_cookies), encoding="utf-8")
            emit(f"Exported {len(latest_cookies)} cookie(s) to {target}")
        else:
            emit(f"Saved session to {target}")
        on_success()
        emit("Done — the secret has been recorded in .env.")

    return runner


# --------------------------------------------------------------------------- #
# job manager                                                                   #
# --------------------------------------------------------------------------- #


@dataclass
class SetupJob:
    id: int
    kind: str           # "install" | "login"
    connector: str
    status: str = "running"  # running | done | error
    error: str | None = None
    started_at: str = field(default_factory=_now_iso)
    finished_at: str | None = None
    log: list[str] = field(default_factory=list)
    _queues: list[Queue] = field(default_factory=list, repr=False)

    def snapshot(self) -> dict[str, Any]:
        return {
            "id": self.id, "kind": self.kind, "connector": self.connector,
            "status": self.status, "error": self.error,
            "started_at": self.started_at, "finished_at": self.finished_at,
            "log": list(self.log),
        }


class SetupManager:
    """Owns the at-most-one active setup job and streams its log lines."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._counter = 0
        self._current: SetupJob | None = None
        self._by_id: dict[int, SetupJob] = {}

    def start(self, kind: str, connector: str, runner: Callable[[Callable[[str], None]], None]) -> SetupJob:
        with self._lock:
            if self._current is not None and self._current.status == "running":
                raise JobAlreadyRunning("a setup task is already running")
            self._counter += 1
            job = SetupJob(id=self._counter, kind=kind, connector=connector)
            self._current = job
            self._by_id[job.id] = job
        threading.Thread(target=self._run, args=(job, runner), daemon=True).start()
        return job

    def _emit(self, job: SetupJob, line: str) -> None:
        with self._lock:
            job.log.append(line)
            for q in job._queues:
                q.put(line)

    def _run(self, job: SetupJob, runner: Callable[[Callable[[str], None]], None]) -> None:
        try:
            runner(lambda line: self._emit(job, line))
            job.status = "done"
        except Exception as exc:  # never crash the server
            job.status = "error"
            job.error = f"{type(exc).__name__}: {exc}"
            self._emit(job, f"[error] {job.error}")
        finally:
            job.finished_at = _now_iso()
            with self._lock:
                queues = list(job._queues)
            for q in queues:
                q.put(_SENTINEL)

    def current(self) -> dict[str, Any] | None:
        with self._lock:
            return self._current.snapshot() if self._current else None

    def get(self, job_id: int) -> dict[str, Any] | None:
        with self._lock:
            job = self._by_id.get(job_id)
            return job.snapshot() if job else None

    def stream(self, job_id: int, *, heartbeat: float = 15.0) -> Iterator[str | None]:
        with self._lock:
            job = self._by_id.get(job_id)
            if job is None:
                return
            buffered = list(job.log)
            finished = job.status != "running"
            q: Queue = Queue()
            if not finished:
                job._queues.append(q)
        try:
            for line in buffered:
                yield line
            if finished:
                return
            while True:
                try:
                    item = q.get(timeout=heartbeat)
                except Empty:
                    yield None
                    continue
                if item is _SENTINEL:
                    return
                yield item
        finally:
            with self._lock:
                if q in job._queues:
                    job._queues.remove(q)


__all__ = [
    "SetupManager",
    "SetupJob",
    "install_commands",
    "run_commands",
    "browser_capture_runner",
    "to_netscape_cookies",
]
